import 'package:flutter/material.dart';
import 'package:idev_viewer/src/internal/theme/themes.dart';

final Map<Color, Map<String, dynamic>> themeFieldStyles = {
  // white 테마 (밝은 배경, 어두운 텍스트)
  Colors.white: {
    'backgroundColor': Colors.white,
    'borderColor': Colors.grey[300]!,
    'labelBackgroundColor': Colors.white,
    'fieldBackgroundColor': Colors.grey[50]!,
    'activatedColor': Colors.grey[200]!,
    'activatedBorderColor': Colors.grey[500]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[200]!,
    'cellColorInReadOnlyState': Colors.white,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.grey[300]!,
  },
  // dark 테마 (어두운 배경, 흰색 텍스트; 셀 배경은 진한 회색 계열)
  Colors.black: {
    'backgroundColor': Colors.grey[900]!,
    'borderColor': Colors.grey[800]!,
    'labelBackgroundColor': Colors.grey[900]!,
    'fieldBackgroundColor': Colors.grey[850]!,
    'activatedColor': Colors.grey[700]!,
    'activatedBorderColor': Colors.white,
    'textStyle': const TextStyle(color: Colors.white),
    'cellColorInEditState': Colors.grey[800]!,
    'cellColorInReadOnlyState': Colors.grey[800]!,
    'iconColor': Colors.white38,
    'disabledIconColor': Colors.white12,
    'menuBackgroundColor': Colors.grey[850]!,
    'inactivatedBorderColor': Colors.grey[800]!,
  },
  // light 테마 (Colors.yellow)
  Colors.yellow: {
    'backgroundColor': Colors.yellow[50]!,
    'borderColor': Colors.grey[400]!,
    'labelBackgroundColor': Colors.yellow[100]!,
    'fieldBackgroundColor': Colors.yellow[50]!,
    'activatedColor': Colors.yellow[300]!,
    'activatedBorderColor': Colors.yellow[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.white,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.grey[400]!,
  },
  // spring 테마 (pink 계열)
  Colors.pink: {
    'backgroundColor': Colors.pink[50]!,
    'borderColor': Colors.pink[200]!,
    'labelBackgroundColor': Colors.pink[100]!,
    'fieldBackgroundColor': Colors.pink[50]!,
    'activatedColor': Colors.pink[300]!,
    'activatedBorderColor': Colors.pink[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.pink[200]!,
  },
  // summer 테마 (blue/lightBlue 계열)
  Colors.blue: {
    'backgroundColor': Colors.lightBlue[50]!,
    'borderColor': Colors.blue[200]!,
    'labelBackgroundColor': Colors.lightBlue[100]!,
    'fieldBackgroundColor': Colors.lightBlue[50]!,
    'activatedColor': Colors.blue[300]!,
    'activatedBorderColor': Colors.blue[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.blue[200]!,
  },
  // autumn 테마 (orange 계열)
  Colors.orange: {
    'backgroundColor': Colors.orange[50]!,
    'borderColor': Colors.orange[200]!,
    'labelBackgroundColor': Colors.orange[100]!,
    'fieldBackgroundColor': Colors.orange[50]!,
    'activatedColor': Colors.orange[300]!,
    'activatedBorderColor': Colors.orange[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.orange[200]!,
  },
  // winter 테마 (blueGrey 계열)
  Colors.blueGrey: {
    'backgroundColor': Colors.blueGrey[50]!,
    'borderColor': Colors.blueGrey[200]!,
    'labelBackgroundColor': Colors.blueGrey[100]!,
    'fieldBackgroundColor': Colors.blueGrey[50]!,
    'activatedColor': Colors.blueGrey[300]!,
    'activatedBorderColor': Colors.blueGrey[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.blueGrey[200]!,
  },
  // nature 테마 (green 계열)
  Colors.green: {
    'backgroundColor': Colors.green[50]!,
    'borderColor': Colors.green[200]!,
    'labelBackgroundColor': Colors.green[100]!,
    'fieldBackgroundColor': Colors.green[50]!,
    'activatedColor': Colors.green[300]!,
    'activatedBorderColor': Colors.green[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.green[200]!,
  },
  // sea 테마 (teal 계열)
  Colors.teal: {
    'backgroundColor': Colors.teal[50]!,
    'borderColor': Colors.teal[200]!,
    'labelBackgroundColor': Colors.teal[100]!,
    'fieldBackgroundColor': Colors.teal[50]!,
    'activatedColor': Colors.teal[300]!,
    'activatedBorderColor': Colors.teal[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.teal[200]!,
  },
  // tree 테마 (brown 계열)
  Colors.brown: {
    'backgroundColor': Colors.brown[50]!,
    'borderColor': Colors.brown[200]!,
    'labelBackgroundColor': Colors.brown[100]!,
    'fieldBackgroundColor': Colors.brown[50]!,
    'activatedColor': Colors.brown[300]!,
    'activatedBorderColor': Colors.brown[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.brown[200]!,
  },
  // universe 테마 (deepPurple 계열)
  Colors.deepPurple: {
    'backgroundColor': Colors.deepPurple[50]!,
    'borderColor': Colors.deepPurple[200]!,
    'labelBackgroundColor': Colors.deepPurple[100]!,
    'fieldBackgroundColor': Colors.deepPurple[50]!,
    'activatedColor': Colors.deepPurple[300]!,
    'activatedBorderColor': Colors.deepPurple[700]!,
    'textStyle': const TextStyle(color: Colors.black),
    'cellColorInEditState': Colors.grey[300]!,
    'cellColorInReadOnlyState': Colors.grey[100]!,
    'iconColor': Colors.black38,
    'disabledIconColor': Colors.black12,
    'menuBackgroundColor': Colors.grey[200]!,
    'inactivatedBorderColor': Colors.deepPurple[200]!,
  },
};

dynamic fieldStyle(String theme, String key) {
  final Color color = themes[theme]!;
  return themeFieldStyles[color]?[key];
}
