name: idev_viewer
description: IDev-based template viewer plugin for Flutter with 100% identical rendering across all platforms (Android, iOS, Web, Windows)
version: 1.0.6
homepage: https://idev.biz
repository: https://github.com/skydbdb/idev-viewer
issue_tracker: https://github.com/skydbdb/idev-viewer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  # idev-app assets (iframe으로 로드되는 빌드된 웹 앱)
  assets:
    - assets/idev-app/
    - assets/idev-app/assets/
    - assets/idev-app/assets/assets/
    - assets/idev-app/assets/assets/icons/
    - assets/idev-app/assets/assets/fonts/
    - assets/idev-app/assets/fonts/
    - assets/idev-app/assets/shaders/
    - assets/idev-app/canvaskit/
    - assets/idev-app/icons/

topics:
  - flutter
  - viewer
  - template
  - idev
  - cross-platform

keywords:
  - flutter
  - viewer
  - template
  - idev
  - cross-platform
  - widget
  - ui
  - android
  - ios
  - web
  - windows
