name: idev_viewer
description: IDev-based template viewer plugin for Flutter with 100% identical rendering across all platforms (Android, iOS, Web, Windows)
version: 1.0.0
homepage: https://idev.biz
repository: https://github.com/skydbdb/idev-viewer
issue_tracker: https://github.com/skydbdb/idev-viewer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
  flutter_web_plugins:
    sdk: flutter
  
  # Core dependencies from idev IDE
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  rxdart: ^0.27.7
  get_it: ^7.6.4
  
  # UI dependencies
  pluto_grid_plus: ^8.3.0
  pluto_menu_bar: ^2.0.1
  pluto_layout: ^1.0.0
  docking: ^1.16.1
  animated_tree_view: ^1.0.0
  flutter_layout_grid: ^2.0.0
  flutter_colorpicker: ^1.1.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.1.2
  material_symbols_icons: ^4.2791.1
  font_awesome_flutter: ^10.2.1
  group_radio_button: ^1.3.0
  
  # Utility dependencies
  dio: ^5.1.2
  http: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  uuid: ^4.5.1
  collection: ^1.19.1
  change_case: ^2.1.0
  package_info_plus: ^9.0.0
  
  # Data handling
  encrypt: ^5.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # Other
  url_launcher: ^6.1.6
  adaptive_dialog: ^2.1.0
  markdown_widget: ^2.3.2+6
  petitparser: ^5.4.0
  flutter_popup_card: ^0.0.6
  pdf: ^3.11.3
  faker: ^2.2.0
  file_saver: ^0.2.14
  sorted_list: ^1.0.0
  flutter_easyloading: ^3.0.5
  easy_sidemenu: ^0.7.1
  geolocator: ^10.1.0
  syncfusion_flutter_charts: ^30.1.38
  csv: ^5.0.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  # Note: assets/viewer-app/ will be created during build process
  # The actual viewer app files should be provided by the user or
  # built using the build-all.sh script

topics:
  - flutter
  - viewer
  - template
  - idev
  - cross-platform

keywords:
  - flutter
  - viewer
  - template
  - idev
  - cross-platform
  - widget
  - ui
  - android
  - ios
  - web
  - windows
